.defcolor blue rgb 0.1f 0.1f 1.0f
.defcolor red  rgb #990000
.color
.TL
Dergods' Style and good practices for C/C++ projects
.AU
Joe
.PP
My cool roff document .
aze&é""
.PP
This is a new paragraph
It this going to be annoying?
I have to save twice.

Is it ok now?
Maybe now?
Ok cool af

Working
qweqwe

Now we can write some text
.PP
Pretty
.CW "\m[red]cool and based\m[]" ,
.gcolor blue
huh
.gcolor
